### ISSUE TITLE
Tags, broken i Internet Explorer

### ISSUE THREAD

**Issue by jorgenskogmo** [tobaccoplaybook/site#3]

**Comment by jorgenskogmo** [comment]
Using https://github.com/xdissent/ievms to install Explorer via VirtualBox on macOS

- WinXP + IE 6, 7, 8 : Fails to load the site. (Also fails to load github.com) (SSL?)
- Win7 + IE 9: **Works as intended**
- Win7 + IE 10: **Works as intended**
- Win7 + IE 11:  **Works as intended**

We could possibly adopt a policy like github's: https://help.github.com/articles/supported-browsers/

**Comment by jorgenskogmo** [comment]
Need to find a way to reproduce the error.

**Comment by gauden** [comment]
We will ask the person who reported this at the meeting. Meantime, indeed, this can be paused.

**Comment by jorgenskogmo** [comment]
Closing this issue (as the redesign has a new tags implementation).
